name: rpd-rnaseq-dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::openjdk=8.0.144 # Needed for FastQC - conda build hangs without this
  - fastqc=0.11.7
  - trim-galore=0.5.0
  - star=2.6.1a
  - picard=2.18.11
  - rseqc=2.6.4
  - multiqc=1.6
  - rsem=1.3.0
  - deeptools=3.1.3
  # samtools=1.3 required by rsem=1.3.0
